
spring:
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: #create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baselineOnMigrate: true
    locations: filesystem:db/migration



  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: surok
    driver-class-name: org.postgresql.Driver
